SRC_FILES_1 := \
  agg-1-fixes.patch \
  agg.mk \
  apr-util.mk \
  apr.mk \
  armadillo-1-staticlib.patch \
  armadillo-test.cpp \
  armadillo.mk \
  arpack.mk \
  atk-1-DllMain.patch \
  atk.mk \
  atkmm.mk \
  aubio-1-fix-pkg-config.patch \
  aubio.mk \
  bfd.mk \
  blas.mk \
  boost-test.cpp \
  boost.mk \
  build-autoconf.mk \
  build-automake.mk \
  build-binutils.mk \
  build-bison.mk \
  build-cmake.mk \
  build-flex.mk \
  build-gcc.mk \
  build-gperf.mk \
  build-libtool.mk \
  build-m4-1-fixes.patch \
  build-m4.mk \
  build-msvctools.mk \
  build-pkg-config-1-fixes.patch \
  build-pkg-config.mk \
  build-texinfo.mk \
  build-xz.mk \
  bzip2.mk \
  cairo-2-static-init.patch \
  cairo.mk \
  cairomm.mk \
  cblas.mk \
  cfitsio.mk \
  cgal-1-fixes.patch \
  cgal.mk \
  cminpack.mk \
  cppunit.mk \
  cunit.mk \
  curl-test.c \
  curl.mk \
  dbus.mk \
  dcmtk-1-fixes.patch \
  dcmtk.mk \
  devil-1-png.patch \
  devil.mk \
  eigen.mk \
  exiv2-issue847.patch \
  exiv2-r2796.patch \
  exiv2.mk \
  expat.mk \
  faad2-1-uint.patch \
  faad2.mk \
  ffmpeg.mk \
  fftw.mk \
  file-test.c \
  file.mk \
  flac-1-win32.patch \
  flac-2-lwsock32.patch \
  flac.mk \
  fltk-1-darwin-cross-compile.patch \
  fltk-2-uuid-mod.patch \
  fltk-test.cpp \
  fltk.mk \
  fontconfig-1.patch \
  fontconfig.mk \
  freeglut-1-fixes.patch \
  freeglut-test.c \
  freeglut.mk \
  freeimage-1-fixes.patch \
  freeimage.mk \
  freetds.mk \
  freetype.mk \
  fribidi-1-fixes.patch \
  fribidi.mk \
  ftgl-1-gl-m4.patch \
  ftgl.mk \
  gc.mk \
  gcab.mk \
  gcc-1-mingw-float.patch \
  gcc-2-darwin-no-pie.patch \
  gcc-gmp.mk \
  gcc-mpc.mk \
  gcc-mpfr.mk \
  gd-1-libpng15.patch \
  gd-test.c \
  gd.mk \
  gdal.mk \
  gdb-1-fix-shell.patch \
  gdb.mk \
  gdcm.mk \
  gdk-pixbuf-1-fixes.patch \
  gdk-pixbuf.mk \
  geos-test.c \
  geos.mk \
  gettext.mk \
  giflib.mk \
  gl2ps-1-fixes.patch \
  gl2ps.mk \
  glew-test.c \
  glew.mk \
  glib.mk \
  glibmm.mk \
  glpk-1-fixes.patch \
  glpk.mk \
  gmp.mk \
  gnuplot-1-fixes.patch \
  gnuplot.mk \
  gnutls-1-fixes.patch \
  gnutls-2-ldadd.patch \
  gnutls-test.c \
  gnutls.mk \
  graphicsmagick-1-fix-xml2-config.patch \
  graphicsmagick-2-fix-png16-config.patch \
  graphicsmagick-test.cpp \
  graphicsmagick.mk \
  gsl-test.c \
  gsl.mk \
  gsoap-1-fixes.patch \
  gsoap.mk \
  gst-plugins-base.mk \
  gst-plugins-good.mk \
  gstreamer.mk \
  gta-test.c \
  gta.mk \
  gtk2-1-fixes.patch \
  gtk2-test.c \
  gtk2.mk \
  gtk3.mk \
  gtkglarea-1-fixes.patch \
  gtkglarea.mk \
  gtkglext-1-fixes.patch \
  gtkglext-test.c \
  gtkglext.mk \
  gtkglextmm-1-fixes.patch \
  gtkglextmm-test.cpp \
  gtkglextmm.mk \
  gtkmm2-test.cpp \
  gtkmm2.mk \
  gtksourceview.mk \
  gtksourceviewmm2.mk \
  guile-1-win32.patch \
  guile-test.c \
  guile.mk \
  harfbuzz.mk \
  hdf5.mk \
  hunspell-test.cpp \
  hunspell.mk \
  id3lib-1-win32.patch \
  id3lib.mk \
  ilmbase-1-gcc45-include.patch \
  ilmbase-2-osx-cxxflags.patch \
  ilmbase.mk \
  imagemagick.mk \
  intltool.mk \
  itsol.mk \
  itstool.mk \
  jasper-1-fixes.patch \
  jasper.mk \
  jpeg-test.c \
  jpeg.mk \
  json-c-1-patch-missingfile.patch \
  json-c-2-patch-remove-rpl.patch \
  json-c-test.c \
  json-c.mk \
  lame.mk \
  lapack-test.f \
  lapack.mk \
  lcms-1-fixes.patch \
  lcms.mk \
  lcms1-1-fixes.patch \
  lcms1.mk \
  levmar.mk \
  libarchive-1-fixes.patch \
  libarchive-test.c \
  libarchive.mk \
  libass-test.c \
  libass.mk \
  libcroco.mk \
  libdnet-1-fixes.patch \
  libdnet.mk \
  libevent.mk \
  libf2c-1.patch \
  libf2c.mk \
  libffi-test.c \
  libffi.mk \
  libgcrypt-test.c \
  libgcrypt.mk \
  libgd.mk \
  libgda.mk \
  libgdamm.mk \
  libgee.mk \
  libgeotiff.mk \
  libglade.mk \
  libgnurx-1-build-static-lib.patch \
  libgnurx.mk \
  libgomp-test.c \
  libgomp.mk \
  libgpg_error-1-fixes.patch \
  libgpg_error.mk \
  libgsasl-1-fixes.patch \
  libgsasl-test.c \
  libgsasl.mk \
  libgsf-1-fixes.patch \
  libgsf.mk \
  libharu-1-fixes.patch \
  libharu.mk \
  libiberty-test.c \
  libiberty.mk \
  libical-test.c \
  libical.mk \
  libiconv-1-fix.patch \
  libiconv.mk \
  libidn-1-fixes.patch \
  libidn-test.c \
  libidn.mk \
  libircclient-1-fixes.patch \
  libircclient-test.cpp \
  libircclient.mk \
  liblo.mk \
  libmad.mk \
  libmikmod-1-fixes.patch \
  libmikmod-test.c \
  libmikmod.mk \
  libmng.mk \
  libmodplug-test.c \
  libmodplug.mk \
  libntlm.mk \
  liboauth-test.c \
  liboauth.mk \
  libodbc++-1-libtool.patch \
  libodbc++-1-win32.patch \
  libodbc++.mk \
  liboil.mk \
  libpano13.mk \
  libpaper.mk \
  libpng-test.c \
  libpng.mk \
  librsvg-1-fixes.patch \
  librsvg-test.c \
  librsvg.mk \
  librtmp-1-v2.4.patch \
  librtmp-2-master.patch \
  librtmp.mk \
  libsamplerate.mk \
  libshout-1-fixes.patch \
  libshout.mk \
  libsigc++.mk \
  libsndfile.mk \
  libssh2-1-fixes.patch \
  libssh2-test.c \
  libssh2.mk \
  libtool.mk \
  libunistring.mk \
  libusb.mk \
  libvpx-1-fixes.patch \
  libvpx.mk \
  libxml++.mk \
  libxml2-1-fixes.patch \
  libxml2.mk \
  libxslt.mk \
  llvm.mk \
  log4cxx-1-gcc.4.4.patch \
  log4cxx-2-pkgconfig.patch \
  log4cxx-3-warnings.patch \
  log4cxx-4-mingw.definitions.patch \
  log4cxx-5-cmake.patch \
  log4cxx-test.cpp \
  log4cxx.mk \
  lua-test.c \
  lua.mk \
  lzo.mk \
  matio.mk \
  mdbtools.mk \
  mingw-cairo-1-ssize-t-defined.patch \
  mingw-cfitsio-1-fixes.patch \
  mingw-glib-1-fixes.patch \
  mingw-glib-2-fixes.patch \
  mingw-hdf5-1.patch \
  mingw-libgcrypt-1-fixes.patch \
  mingw-libmng-1-noundefines.patch \
  mingw-openssl-3-libdeps.patch \
  mingw-pango-1-fixes.patch \
  mingw-transfig-1-configure.patch \
  mingw-units-1-fixes.patch \
  mingw-utils-1-portability-fix.patch \
  mingw-utils.mk \
  mingwrt.mk \
  mpfr.mk \
  msitools.mk \
  msvc-atk-1.patch \
  msvc-build-cmake-1.patch \
  msvc-cairo-1.patch \
  msvc-curl-1.patch \
  msvc-dbus-1.patch \
  msvc-fftw-1.patch \
  msvc-fltk-1.patch \
  msvc-fontconfig-1.patch \
  msvc-gcab-1.patch \
  msvc-gdk-pixbuf-1.patch \
  msvc-gettext-1.patch \
  msvc-gl2ps-1.patch \
  msvc-glib-1.patch \
  msvc-gnuplot-1.patch \
  msvc-gnutls-1.patch \
  msvc-graphicsmagick-1.patch \
  msvc-gsl-1.patch \
  msvc-gtk3-1.patch \
  msvc-harfbuzz-1.patch \
  msvc-hdf5-1.patch \
  msvc-itsol-1.patch \
  msvc-itstool-1.patch \
  msvc-libffi-1.patch \
  msvc-libgcrypt-1.patch \
  msvc-libgd-1.patch \
  msvc-libgpg_error-1.patch \
  msvc-libgsf-1.patch \
  msvc-libiconv-1.patch \
  msvc-libidn-1.patch \
  msvc-libmng-1.patch \
  msvc-libssh2-1.patch \
  msvc-libxml2-1.patch \
  msvc-llvm-1.patch \
  msvc-msitools-1.patch \
  msvc-msitools-2-tests.patch \
  msvc-ncurses-1.patch \
  msvc-netcdf-1.patch \
  msvc-nettle-1.patch \
  msvc-octave-1.patch \
  msvc-of-image-1.patch \
  msvc-of-miscellaneous-1.patch \
  msvc-openssl-1.patch \
  msvc-openssl-3-libdeps.patch \
  msvc-pango-1.patch \
  msvc-pixman-1.patch \
  msvc-proj-1.patch \
  msvc-pstoedit-1.patch \
  msvc-qhull-1.patch \
  msvc-qt-1.patch \
  msvc-readline-1.patch \
  msvc-suitesparse-1.patch \
  msvc-texinfo-1.patch \
  msvc-tiff-1.patch \
  msvc-vala-1.patch \
  msvc-zenity-1.patch \
  msys-bash.mk \
  msys-coreutils.mk \
  msys-diffutils.mk \
  msys-dos2unix.mk \
  msys-file.mk \
  msys-findutils.mk \
  msys-gawk.mk \
  msys-grep.mk \
  msys-gzip.mk \
  msys-less.mk \
  msys-libiconv.mk \
  msys-libintl.mk \
  msys-libmagic.mk \
  msys-make.mk \
  msys-msys-core.mk \
  msys-patch.mk \
  msys-regex.mk \
  msys-sed.mk \
  msys-tar.mk \
  msys-termcap.mk \
  msys-texinfo.mk \
  msys-unzip.mk \
  msys-wget.mk \
  msys-xz.mk \
  muparser.mk \
  mxml-test.c \
  mxml.mk \
  native-binutils.mk \
  native-gcc-1-float.patch \
  native-gcc.mk \
  ncurses.mk \
  netcdf.mk \
  nettle-1-fixes.patch \
  nettle.mk \
  npp.mk \
  nsis-1-fixes.patch \
  nsis.mk \
  ocaml-core-1-fixes.patch \
  ocaml-core-test.ml \
  ocaml-core.mk \
  ocaml-flexdll-1-fixes.patch \
  ocaml-flexdll-test.c \
  ocaml-flexdll.mk \
  ocaml-native-1-fixes.patch \
  ocaml-native.mk \
  octave.mk \
  of-actuarial.mk \
  of-communications.mk \
  of-control.mk \
  of-data-smoothing.mk \
  of-dicom.mk \
  of-fits-1-fixes.patch \
  of-fits.mk \
  of-fl-core-1-fixes.patch \
  of-fl-core.mk \
  of-fuzzy-logic-toolkit.mk \
  of-general.mk \
  of-geometry.mk \
  of-image.mk \
  of-io.mk \
  of-linear-algebra.mk \
  of-miscellaneous.mk \
  of-odepkg.mk \
  of-optim-1-fixes.patch \
  of-optim.mk \
  of-quaternion.mk \
  of-signal.mk \
  of-sockets-1-fixes.patch \
  of-sockets.mk \
  of-specfun.mk \
  of-statistics.mk \
  of-struct.mk \
  of-tsa.mk \
  of-windows.mk \
  of-zenity.mk \
  ogg.mk \
  old.mk \
  openal-1-fixes.patch \
  openal-test.c \
  openal.mk \
  openblas.mk \
  opencore-amr.mk \
  opencsg-1-fixes.patch \
  opencsg.mk \
  openexr-1-disable-zlib_winapi.patch \
  openexr.mk \
  openscenegraph.mk \
  openssl-1-winsock2.patch \
  openssl-2-pod.patch \
  openssl.mk \
  pango.mk \
  pangomm.mk \
  pcre.mk \
  pdcurses.mk \
  pdflib_lite-1-mingw.patch \
  pdflib_lite.mk \
  pfstools.mk \
  physfs-test.c \
  physfs.mk \
  pixman.mk \
  pkg-config.mk \
  plibc.mk \
  plotmm-1-fixes.patch \
  plotmm.mk \
  plotutils-2.6-libpng-1.5.patch \
  plotutils.mk \
  poco-1-fix-mno-cygwin.patch \
  poco-test.cpp \
  poco.mk \
  poppler-1-win32.patch \
  poppler-test.cxx \
  poppler.mk \
  popt-1-win32.patch \
  popt.mk \
  portaudio-1-win32.patch \
  portaudio-test.c \
  portaudio.mk \
  postgresql-1-fixes.patch \
  postgresql.mk \
  proj.mk \
  protobuf-test.cpp \
  protobuf.mk \
  pstoedit-1-fixes.patch \
  pstoedit-2-gs.patch \
  pstoedit.mk \
  pthreads-1-fixes.patch \
  pthreads-test.c \
  pthreads.mk \
  qdbm-test.c \
  qdbm.mk \
  qhull-1-fixes.patch \
  qhull-2-fixes.patch \
  qhull.mk \
  qjson-1-static.patch \
  qjson.mk \
  qrupdate-1-fixes.patch \
  qrupdate.mk \
  qscintilla-1-fixes.patch \
  qscintilla-2-bang-fix.patch \
  qscintilla.mk \
  qt-1-cherrypicks.patch \
  qt-1-pcre.patch \
  qt-2-dbus.patch \
  qt-test.cpp \
  qt-test.pro \
  qt-test.ui \
  qt.mk \
  qwt-1-fixes.patch \
  qwt.mk \
  qwtplot3d-1-fixes.patch \
  qwtplot3d.mk \
  readline-1-binding.patch \
  readline-1-display.patch \
  readline-1-input.patch \
  readline-1-paste.patch \
  readline-1-sigwinch.patch \
  readline-2-event-hook.patch \
  readline.mk \
  sdl-test.c \
  sdl.mk \
  sdl_image-test.c \
  sdl_image.mk \
  sdl_mixer-test.c \
  sdl_mixer.mk \
  sdl_net-1-fixes.patch \
  sdl_net-test.c \
  sdl_net.mk \
  sdl_pango-1-api-adds.patch \
  sdl_pango-2-static-matrices.patch \
  sdl_pango.mk \
  sdl_sound-test.c \
  sdl_sound.mk \
  sdl_ttf.mk \
  smpeg-test.c \
  smpeg.mk \
  sox-test.c \
  sox.mk \
  speex.mk \
  sqlite.mk \
  stable-octave.mk \
  suitesparse-1.patch \
  suitesparse.mk \
  t4k_common.mk \
  taglib-1-static.patch \
  taglib.mk \
  termcap-1-fixes.patch \
  termcap.mk \
  texinfo.mk \
  theora.mk \
  tiff.mk \
  tinyxml-test.cpp \
  tinyxml.mk \
  transfig.mk \
  tre.mk \
  units-1-fixes.patch \
  units.mk \
  uuid.mk \
  vala.mk \
  vigra-test.cpp \
  vigra.mk \
  vmime-1-fixes.patch \
  vmime.mk \
  vorbis.mk \
  vtk-1-tryrun.patch \
  vtk-2-findfreetype.patch \
  vtk-3-compile-tools.patch \
  vtk-4-native-no-gui.patch \
  vtk-5-module-path.patch \
  vtk-6-kfreebsd.patch \
  vtk.mk \
  w32api-1-dinput-dsound.patch \
  w32api-2-directx-additions-for-qt.patch \
  w32api.mk \
  wget.mk \
  winpcap-1-fixes.patch \
  winpcap.mk \
  wt-1-fixes.patch \
  wt.mk \
  wxwidgets-test.cpp \
  wxwidgets.mk \
  x264-1-fix-bin-bash.patch \
  x264.mk \
  xapian-core.mk \
  xerces-1-fix-pkgconfig.patch \
  xerces-test.cpp \
  xerces.mk \
  xine-lib-1-fixes.patch \
  xine-lib.mk \
  xmlwrapp.mk \
  xvidcore-1-fixes.patch \
  xvidcore.mk \
  xz.mk \
  zenity.mk \
  zlib-1-win32-static.patch \
  zlib.mk \
  zziplib-1-fix-fnmatch.patch \
  zziplib.mk

SRC_FILES := $(addprefix src/, $(SRC_FILES_1))

SRC_MSVCTOOLS_FILES_1 := \
  ar-msvc \
  cc-msvc.cc \
  fixlibtool2.in \
  gcc.diff \
  gfortran-msvc.cc \
  libgfortran-dllinit.c \
  libgfortran-msvcinit.c \
  lt-postproc \
  Makefile \
  ranlib-msvc \
  stdbool.h \
  unistd.h \
  Windows-clg++.cmake \
  Windows-clgcc.cmake.in

SRC_MSVCTOOLS_FILES := $(addprefix src/build-msvctools/, $(SRC_MSVCTOOLS_FILES_1))

SRC_MSVCTOOLS_COMPAT_FILES_1 := \
  cabsf.c \
  ccos.c \
  ccosf.c \
  cexp.c \
  cexpf.c \
  clog.c \
  clogf.c \
  csin.c \
  csinf.c \
  csqrt.c \
  csqrtf.c \
  gettimeofday.c \
  Makefile \
  mingwcompat.c \
  mingwcompat_gcc.c \
  usleep.c

SRC_MSVCTOOLS_COMPAT_FILES := \
  $(addprefix src/build-msvctools/compat/, $(SRC_MSVCTOOLS_COMPAT_FILES_1))

SRC_MSVCTOOLS_MATH_FILES_1 := \
  acosh.c \
  acoshf.c \
  asinh.c \
  asinhf.c \
  atanh.c \
  atanhf.c \
  cbrt.c \
  cbrtf.c \
  cephes_mconf.h \
  exp2f.S \
  exp2.S \
  expm1.c \
  expm1f.c \
  fastmath.h \
  finite.c \
  finitef.c \
  fmaf.S \
  fma.S \
  fpclassify.c \
  fpclassifyf.c \
  funx.c \
  ilogbf.S \
  ilogb.S \
  isinf.c \
  isinff.c \
  isnan.c \
  isnanf.c \
  llrint.c \
  llrintf.c \
  log1pf.S \
  log1p.S \
  log2f.S \
  log2.S \
  logb.c \
  logbf.c \
  lrint.c \
  lrintf.c \
  lround_generic.c \
  Makefile \
  math.def \
  math.h.in \
  modff.c \
  nan.c \
  nearbyintf.S \
  nearbyint.S \
  nextafter.c \
  nextafterf.c \
  remainderf.S \
  remainder.S \
  rint.c \
  rintf.c \
  round_generic.c \
  round_internal.h \
  scalbnf.S \
  scalbn.S \
  trunc.c \
  truncf.c

SRC_MSVCTOOLS_MATH_FILES := \
  $(addprefix src/build-msvctools/math/, $(SRC_MSVCTOOLS_MATH_FILES_1))

TOOLS_FILES_1 := \
  build-make.sh \
  config.guess \
  config.sub \
  create-screenshot-for-doc \
  install-sh \
  make-shared-from-static \
  patch-tool-mxe \
  s3-fetch-and-sync \
  set-mxe-env.sh.in

TOOLS_FILES := $(addprefix tools/, $(TOOLS_FILES_1))

FILES := \
  CNAME \
  binary-dist-rules.mk \
  build_packages.m \
  configure \
  configure.ac \
  dist-files.mk \
  index.html \
  Makefile.in \
  makeinst-script.sh \
  octaverc

INSTALL_FILES_1 := \
  gpl-3.0.txt \
  octave.bmp \
  octave-hdr.bmp \
  octave-logo.ico
INSTALL_FILES := $(addprefix installer-files/, $(INSTALL_FILES_1))

DIST_FILES := \
  $(SRC_FILES) \
  $(SRC_MSVCTOOLS_FILES) \
  $(SRC_MSVCTOOLS_COMPAT_FILES) \
  $(SRC_MSVCTOOLS_MATH_FILES) \
  $(TOOLS_FILES) \
  $(FILES) \
  $(INSTALL_FILES)
