SRC_FILES_1 := \
  agg-1-fixes.patch \
  agg.mk \
  apr.mk \
  apr-util.mk \
  armadillo-1-staticlib.patch \
  armadillo.mk \
  armadillo-test.cpp \
  arpack.mk \
  atk-1-DllMain.patch \
  atk.mk \
  atkmm.mk \
  aubio-1-fix-pkg-config.patch \
  aubio.mk \
  bfd.mk \
  blas.mk \
  boost.mk \
  boost-test.cpp \
  build-autoconf.mk \
  build-automake.mk \
  build-binutils.mk \
  build-bison.mk \
  build-cmake.mk \
  build-flex.mk \
  build-gcc.mk \
  build-gperf.mk \
  build-libtool.mk \
  build-pkg-config-1-fixes.patch \
  build-pkg-config.mk \
  build-texinfo.mk \
  bzip2.mk \
  cairo-1-ssize-t-defined.patch \
  cairo-2-static-init.patch \
  cairo.mk \
  cairomm.mk \
  cblas.mk \
  cgal-1-fixes.patch \
  cgal.mk \
  cminpack.mk \
  cppunit.mk \
  cunit.mk \
  curl.mk \
  curl-test.c \
  dbus-1-fixes.patch \
  dbus.mk \
  dcmtk-1-fixes.patch \
  dcmtk.mk \
  devil-1-png.patch \
  devil.mk \
  eigen.mk \
  exiv2-issue847.patch \
  exiv2.mk \
  exiv2-r2796.patch \
  expat.mk \
  faad2-1-uint.patch \
  faad2.mk \
  ffmpeg.mk \
  fftw.mk \
  file.mk \
  file-test.c \
  flac-1-win32.patch \
  flac-2-lwsock32.patch \
  flac.mk \
  fltk-1-darwin-cross-compile.patch \
  fltk-2-uuid-mod.patch \
  fltk.mk \
  fltk-test.cpp \
  fontconfig.mk \
  freeglut-1-fixes.patch \
  freeglut.mk \
  freeglut-test.c \
  freeimage-1-fixes.patch \
  freeimage.mk \
  freetype.mk \
  fribidi-1-fixes.patch \
  fribidi.mk \
  ftgl-1-gl-m4.patch \
  ftgl.mk \
  gcc-1-mingw-float.patch \
  gcc-2-darwin-no-pie.patch \
  gcc-gmp.mk \
  gcc-mpc.mk \
  gcc-mpfr.mk \
  gc.mk \
  gd-1-libpng15.patch \
  gdal.mk \
  gdb-1-fix-shell.patch \
  gdb.mk \
  gdk-pixbuf-1-fixes.patch \
  gdk-pixbuf.mk \
  gd.mk \
  gd-test.c \
  geos.mk \
  geos-test.c \
  gettext.mk \
  giflib.mk \
  glew.mk \
  glew-test.c \
  glib-1-fixes.patch \
  glib.mk \
  glibmm.mk \
  glpk-1-fixes.patch \
  glpk.mk \
  gmp.mk \
  gnuplot-1-fixes.patch \
  gnuplot.mk \
  gnutls-1-fixes.patch \
  gnutls.mk \
  gnutls-test.c \
  graphicsmagick-1-fix-xml2-config.patch \
  graphicsmagick.mk \
  graphicsmagick-test.cpp \
  gsl.mk \
  gsl-test.c \
  gsoap-1-fixes.patch \
  gsoap.mk \
  gst-plugins-base.mk \
  gst-plugins-good.mk \
  gstreamer.mk \
  gta.mk \
  gta-test.c \
  gtk2-1-fixes.patch \
  gtk2.mk \
  gtk2-test.c \
  gtkglarea-1-fixes.patch \
  gtkglarea.mk \
  gtkglext-1-fixes.patch \
  gtkglext.mk \
  gtkglextmm-1-fixes.patch \
  gtkglextmm.mk \
  gtkglextmm-test.cpp \
  gtkglext-test.c \
  gtkmm2.mk \
  gtkmm2-test.cpp \
  gtksourceview.mk \
  gtksourceviewmm2.mk \
  guile-1-win32.patch \
  guile.mk \
  guile-test.c \
  harfbuzz.mk \
  hdf5-1-cross-fixes.patch \
  hdf5.mk \
  hunspell.mk \
  hunspell-test.cpp \
  id3lib-1-win32.patch \
  id3lib.mk \
  ilmbase-1-gcc45-include.patch \
  ilmbase-2-osx-cxxflags.patch \
  ilmbase.mk \
  imagemagick.mk \
  jasper-1-fixes.patch \
  jasper.mk \
  jpeg.mk \
  jpeg-test.c \
  json-c-1-patch-missingfile.patch \
  json-c-2-patch-remove-rpl.patch \
  json-c.mk \
  json-c-test.c \
  lame.mk \
  lapack.mk \
  lapack-test.f \
  lcms1-1-fixes.patch \
  lcms-1-fixes.patch \
  lcms1.mk \
  lcms.mk \
  levmar.mk \
  libarchive-1-fixes.patch \
  libarchive.mk \
  libarchive-test.c \
  libass.mk \
  libass-test.c \
  libcroco.mk \
  libdnet-1-fixes.patch \
  libdnet.mk \
  libevent.mk \
  libf2c-1.patch \
  libf2c.mk \
  libffi.mk \
  libffi-test.c \
  libgcrypt-1-fixes.patch \
  libgcrypt.mk \
  libgcrypt-test.c \
  libgda.mk \
  libgdamm.mk \
  libgee.mk \
  libgeotiff.mk \
  libglade.mk \
  libgnurx-1-build-static-lib.patch \
  libgnurx.mk \
  libgomp.mk \
  libgomp-test.c \
  libgpg_error-1-fixes.patch \
  libgpg_error.mk \
  libgsasl-1-fixes.patch \
  libgsasl.mk \
  libgsasl-test.c \
  libgsf-1-fixes.patch \
  libgsf.mk \
  libharu-1-fixes.patch \
  libharu.mk \
  libiberty.mk \
  libiberty-test.c \
  libical.mk \
  libical-test.c \
  libiconv.mk \
  libidn-1-fixes.patch \
  libidn.mk \
  libidn-test.c \
  libircclient-1-fixes.patch \
  libircclient.mk \
  libircclient-test.cpp \
  liblo.mk \
  libmad.mk \
  libmikmod-1-fixes.patch \
  libmikmod.mk \
  libmikmod-test.c \
  libmng-1-fixes.patch \
  libmng-1-libtool.patch \
  libmng.mk \
  libmodplug.mk \
  libmodplug-test.c \
  libntlm.mk \
  liboauth.mk \
  liboauth-test.c \
  liboil.mk \
  libpano13.mk \
  libpaper.mk \
  libpng.mk \
  libpng-test.c \
  librsvg-1-fixes.patch \
  librsvg.mk \
  librsvg-test.c \
  librtmp-1-v2.4.patch \
  librtmp-2-master.patch \
  librtmp.mk \
  libsamplerate.mk \
  libshout-1-fixes.patch \
  libshout.mk \
  libsigc++.mk \
  libsndfile.mk \
  libssh2-1-fixes.patch \
  libssh2.mk \
  libssh2-test.c \
  libtool.mk \
  libunistring.mk \
  libusb.mk \
  libvpx-1-fixes.patch \
  libvpx.mk \
  libxml2-1-fixes.patch \
  libxml2.mk \
  libxml++.mk \
  libxslt.mk \
  llvm-1-fixes.patch \
  llvm.mk \
  log4cxx-1-gcc.4.4.patch \
  log4cxx-2-pkgconfig.patch \
  log4cxx-3-warnings.patch \
  log4cxx-4-mingw.definitions.patch \
  log4cxx-5-cmake.patch \
  log4cxx.mk \
  log4cxx-test.cpp \
  lua.mk \
  lua-test.c \
  lzo.mk \
  matio.mk \
  mdbtools.mk \
  mingwrt.mk \
  mingw-utils-1-portability-fix.patch \
  mingw-utils.mk \
  mpfr.mk \
  msys-bash.mk \
  msys-coreutils.mk \
  msys-diffutils.mk \
  msys-file.mk \
  msys-findutils.mk \
  msys-gawk.mk \
  msys-grep.mk \
  msys-gzip.mk \
  msys-less.mk \
  msys-libiconv.mk \
  msys-libintl.mk \
  msys-libmagic.mk \
  msys-make.mk \
  msys-msys-core.mk \
  msys-regex.mk \
  msys-sed.mk \
  msys-tar.mk \
  msys-termcap.mk \
  msys-texinfo.mk \
  msys-xz.mk \
  muparser.mk \
  mxml.mk \
  mxml-test.c \
  native-binutils.mk \
  native-gcc-1-float.patch \
  native-gcc.mk \
  ncurses.mk \
  nettle.mk \
  npp.mk \
  nsis-1-fixes.patch \
  nsis.mk \
  ocaml-core-1-fixes.patch \
  ocaml-core.mk \
  ocaml-core-test.ml \
  ocaml-flexdll-1-fixes.patch \
  ocaml-flexdll.mk \
  ocaml-flexdll-test.c \
  ocaml-native-1-fixes.patch \
  ocaml-native.mk \
  octave.mk \
  of-communications-1-fixes.patch \
  of-communications.mk \
  of-control.mk \
  of-general.mk \
  of-image.mk \
  of-io.mk \
  of-miscellaneous.mk \
  of-optim-1-fixes.patch \
  of-optim.mk \
  of-signal.mk \
  of-specfun.mk \
  of-statistics.mk \
  of-struct.mk \
  of-windows.mk \
  ogg.mk \
  old.mk \
  openal-1-fixes.patch \
  openal.mk \
  openal-test.c \
  opencore-amr.mk \
  opencsg-1-fixes.patch \
  opencsg.mk \
  openexr-1-disable-zlib_winapi.patch \
  openexr.mk \
  openscenegraph.mk \
  openssl-1-winsock2.patch \
  openssl.mk \
  pango-1-fixes.patch \
  pango.mk \
  pangomm.mk \
  pcre.mk \
  pdcurses.mk \
  pdflib_lite-1-mingw.patch \
  pdflib_lite.mk \
  pfstools.mk \
  physfs.mk \
  physfs-test.c \
  pixman.mk \
  plibc.mk \
  plotmm-1-fixes.patch \
  plotmm.mk \
  plotutils-2.6-libpng-1.5.patch \
  plotutils.mk \
  poco-1-fix-mno-cygwin.patch \
  poco.mk \
  poco-test.cpp \
  poppler-1-win32.patch \
  poppler.mk \
  poppler-test.cxx \
  popt-1-win32.patch \
  popt.mk \
  portaudio-1-win32.patch \
  portaudio.mk \
  portaudio-test.c \
  proj.mk \
  protobuf.mk \
  protobuf-test.cpp \
  pstoedit-1-fixes.patch \
  pstoedit.mk \
  pthreads-1-fixes.patch \
  pthreads.mk \
  pthreads-test.c \
  qdbm.mk \
  qdbm-test.c \
  qhull-1-fixes.patch \
  qhull-2-fixes.patch \
  qhull.mk \
  qjson-1-static.patch \
  qjson.mk \
  qrupdate-1-fixes.patch \
  qrupdate.mk \
  qscintilla.mk \
  qt-1-cherrypicks.patch \
  qt-1-pcre.patch \
  qt.mk \
  qt-test.cpp \
  qt-test.pro \
  qt-test.ui \
  qwt-1-fixes.patch \
  qwt.mk \
  qwtplot3d-1-fixes.patch \
  qwtplot3d.mk \
  readline-1-binding.patch \
  readline-1-display.patch \
  readline-1-input.patch \
  readline-1-paste.patch \
  readline-1-sigwinch.patch \
  readline.mk \
  sdl_image.mk \
  sdl_image-test.c \
  sdl_mixer.mk \
  sdl_mixer-test.c \
  sdl.mk \
  sdl_net-1-fixes.patch \
  sdl_net.mk \
  sdl_net-test.c \
  sdl_pango-1-api-adds.patch \
  sdl_pango-2-static-matrices.patch \
  sdl_pango.mk \
  sdl_sound.mk \
  sdl_sound-test.c \
  sdl-test.c \
  sdl_ttf.mk \
  smpeg.mk \
  smpeg-test.c \
  sox.mk \
  sox-test.c \
  speex.mk \
  stable-octave.mk \
  suitesparse-1.patch \
  suitesparse.mk \
  t4k_common.mk \
  taglib-1-static.patch \
  taglib.mk \
  termcap-1-fixes.patch \
  termcap.mk \
  texinfo.mk \
  theora.mk \
  tiff.mk \
  tinyxml.mk \
  tinyxml-test.cpp \
  tre.mk \
  uuid.mk \
  vigra.mk \
  vigra-test.cpp \
  vmime-1-fixes.patch \
  vmime.mk \
  vorbis.mk \
  vtk-1-tryrun.patch \
  vtk-2-findfreetype.patch \
  vtk-3-compile-tools.patch \
  vtk-4-native-no-gui.patch \
  vtk-5-module-path.patch \
  vtk-6-kfreebsd.patch \
  vtk.mk \
  w32api-1-dinput-dsound.patch \
  w32api-2-directx-additions-for-qt.patch \
  w32api.mk \
  wget.mk \
  winpcap-1-fixes.patch \
  winpcap.mk \
  wt-1-fixes.patch \
  wt.mk \
  wxwidgets.mk \
  wxwidgets-test.cpp \
  x264-1-fix-bin-bash.patch \
  x264.mk \
  xapian-core.mk \
  xerces-1-fix-pkgconfig.patch \
  xerces.mk \
  xerces-test.cpp \
  xine-lib-1-fixes.patch \
  xine-lib.mk \
  xmlwrapp.mk \
  xvidcore-1-fixes.patch \
  xvidcore.mk \
  xz.mk \
  zlib-1-win32-static.patch \
  zlib.mk \
  zziplib-1-fix-fnmatch.patch \
  zziplib.mk

SRC_FILES := $(addprefix src/, $(SRC_FILES_1))

TOOLS_FILES_1 := \
  config.guess \
  config.sub \
  create-screenshot-for-doc \
  install-sh \
  make-shared-from-static \
  patch-tool-mxe \
  s3-fetch-and-sync

TOOLS_FILES := $(addprefix tools/, $(TOOLS_FILES_1))

FILES := \
  build_packages.m \
  CNAME \
  configure \
  configure.ac \
  dist-files.mk \
  index.html \
  Makefile.in \
  makeinst-script.sh \
  mk-dist \
  octaverc

DOC_FILES_1 := \
  screenshot-4th-compile.png \
  screenshot-4th-compile-small.png \
  screenshot-4th-run.png \
  screenshot-4th-run-small.png

DOC_FILES := $(addprefix doc/, $(DOC_FILES_1))

DIST_FILES := $(SRC_FILES) $(TOOLS_FILES) $(FILES) $(DOC_FILES)
