SRC_FILES_1 := \
  a52dec.mk \
  agg-1-fixes.patch \
  agg.mk \
  apr-util.mk \
  apr.mk \
  armadillo-1-staticlib.patch \
  armadillo-test.cpp \
  armadillo.mk \
  arpack.mk \
  atk-1-DllMain.patch \
  atk.mk \
  atkmm.mk \
  aubio-1-fix-pkg-config.patch \
  aubio.mk \
  bfd.mk \
  blas.mk \
  blas_switch.mk \
  boost-1-intrinsics-fix.patch \
  boost-2-winerror.patch \
  boost-test.cpp \
  boost.mk \
  build-autoconf.mk \
  build-automake.mk \
  build-binutils.mk \
  build-bison.mk \
  build-cmake.mk \
  build-flex-1-fixes.patch \
  build-flex.mk \
  build-gawk.mk \
  build-gcc.mk \
  build-gettext.mk \
  build-gperf.mk \
  build-libtool.mk \
  build-lzip.mk \
  build-m4-glibc2-28.patch \
  build-m4.mk \
  build-mako.mk \
  build-markupsafe.mk \
  build-msvctools.mk \
  build-perl.mk \
  build-pkg-config-1-fixes.patch \
  build-pkg-config.mk \
  build-python.mk \
  build-scons.mk \
  build-sed.mk \
  build-setuptools.mk \
  build-texinfo.mk \
  build-xz.mk \
  build-yasm.mk \
  bzip2-1-fixes.patch \
  bzip2.mk \
  c-ares.mk \
  cairo-2-static-init.patch \
  cairo.mk \
  cairomm.mk \
  cblas.mk \
  cfitsio.mk \
  cgal-1-fixes.patch \
  cgal.mk \
  cloog.mk \
  cmake.mk \
  cminpack.mk \
  cppunit.mk \
  cunit.mk \
  curl-test.c \
  curl.mk \
  damageproto.mk \
  dbus-1-fixes.patch \
  dbus.mk \
  dcmtk-1-fixes.patch \
  dcmtk-2-mingw-w64.patch \
  dcmtk-3-pointer-fixes.patch \
  dcmtk-4-c++11-related-fixes.patch \
  dcmtk.mk \
  default-octave-1-gnulib.patch \
  default-octave.mk \
  devil-1-png.patch \
  devil.mk \
  double-conversion.mk \
  dri2proto.mk \
  eigen.mk \
  epstool.mk \
  exiv2-issue847.patch \
  exiv2-r2796.patch \
  exiv2.mk \
  expat.mk \
  faad2-1-fixes.patch \
  faad2.mk \
  ffmpeg.mk \
  fftw.mk \
  file-test.c \
  file.mk \
  fixesproto.mk \
  flac.mk \
  fltk-2-uuid-mod.patch \
  fltk-test.cpp \
  fltk.mk \
  fontconfig.mk \
  freeglut-1-fixes.patch \
  freeglut-test.c \
  freeglut.mk \
  freeimage-1-fixes.patch \
  freeimage.mk \
  freetds.mk \
  freetype.mk \
  fribidi.mk \
  ftgl-1-gl-m4.patch \
  ftgl.mk \
  gc.mk \
  gcab.mk \
  gcc-cloog.mk \
  gcc-gmp.mk \
  gcc-isl.mk \
  gcc-mpc.mk \
  gcc-mpfr.mk \
  gd-1-libpng15.patch \
  gd-test.c \
  gd.mk \
  gdal.mk \
  gdb.mk \
  gdcm-1-nosecapi.patch \
  gdcm.mk \
  gdk-pixbuf-1-fixes.patch \
  gdk-pixbuf.mk \
  geos-test.c \
  geos.mk \
  gettext-1.patch \
  gettext.mk \
  ghostscript-1-fixes.patch \
  ghostscript.mk \
  giflib.mk \
  gl2ps-1-configure.patch \
  gl2ps-2-docpath.patch \
  gl2ps.mk \
  glew-test.c \
  glew.mk \
  glib-1-fixes.patch \
  glib.mk \
  glibmm.mk \
  glpk-1-fixes.patch \
  glpk.mk \
  glproto.mk \
  glu.mk \
  gmp.mk \
  gnuplot-1-fixes.patch \
  gnuplot.mk \
  gnutls-1-fixes.patch \
  gnutls-test.c \
  gnutls.mk \
  graphicsmagick-1-fix-xml2-config.patch \
  graphicsmagick-2-dynamicpath.patch \
  graphicsmagick-test.cpp \
  graphicsmagick.mk \
  gsl-test.c \
  gsl.mk \
  gsoap-1-fixes.patch \
  gsoap.mk \
  gst-plugins-base.mk \
  gst-plugins-good.mk \
  gstreamer.mk \
  gta-test.c \
  gta.mk \
  gtk2-1-fixes.patch \
  gtk2-test.c \
  gtk2.mk \
  gtk3.mk \
  gtkglarea-1-fixes.patch \
  gtkglarea.mk \
  gtkglext-1-fixes.patch \
  gtkglext-test.c \
  gtkglext.mk \
  gtkglextmm-1-fixes.patch \
  gtkglextmm-test.cpp \
  gtkglextmm.mk \
  gtkmm2-test.cpp \
  gtkmm2.mk \
  gtksourceview.mk \
  gtksourceviewmm2.mk \
  guile-1-win32.patch \
  guile-test.c \
  guile.mk \
  harfbuzz.mk \
  hdf5.mk \
  hunspell-test.cpp \
  hunspell.mk \
  ice.mk \
  icu4c.mk \
  id3lib-1-win32.patch \
  id3lib.mk \
  ilmbase.mk \
  imagemagick.mk \
  inputproto.mk \
  intltool.mk \
  isl.mk \
  itsol.mk \
  itstool.mk \
  jasper-1-fixes.patch \
  jasper.mk \
  jpeg-test.c \
  jpeg.mk \
  json-c-1-patch-missingfile.patch \
  json-c-2-patch-remove-rpl.patch \
  json-c-test.c \
  json-c.mk \
  kbproto.mk \
  lame-1-fixes.patch \
  lame.mk \
  lapack-test.f \
  lapack.mk \
  lcms-1-fixes.patch \
  lcms.mk \
  lcms1-1-fixes.patch \
  lcms1.mk \
  levmar.mk \
  libarchive-1-fixes.patch \
  libarchive-test.c \
  libarchive.mk \
  libass-test.c \
  libass.mk \
  libbiosig.mk \
  libcdio.mk \
  libcroco.mk \
  libdnet-1-fixes.patch \
  libdnet.mk \
  libdrm.mk \
  libevent.mk \
  libf2c-1.patch \
  libf2c.mk \
  libffi-test.c \
  libffi.mk \
  libgcrypt-test.c \
  libgcrypt.mk \
  libgd.mk \
  libgda.mk \
  libgdamm.mk \
  libgee.mk \
  libgeotiff.mk \
  libglade.mk \
  libgnurx-1-build-static-lib.patch \
  libgnurx.mk \
  libgomp-test.c \
  libgomp.mk \
  libgpg_error-1-fixes.patch \
  libgpg_error.mk \
  libgsasl-1-fixes.patch \
  libgsasl-test.c \
  libgsasl.mk \
  libgsf-1-fixes.patch \
  libgsf.mk \
  libharu-1-fixes.patch \
  libharu.mk \
  libiberty-test.c \
  libiberty.mk \
  libical-test.c \
  libical.mk \
  libiconv.mk \
  libidn-1-fixes.patch \
  libidn-test.c \
  libidn.mk \
  libidn2.mk \
  libircclient-1-fixes.patch \
  libircclient-test.cpp \
  libircclient.mk \
  libjbig.mk \
  liblo.mk \
  libmad.mk \
  libmikmod-1-fixes.patch \
  libmikmod-test.c \
  libmikmod.mk \
  libmng.mk \
  libmodplug-test.c \
  libmodplug.mk \
  libmpcdec-1-configure_ac.patch \
  libmpcdec.mk \
  libntlm.mk \
  liboauth-test.c \
  liboauth.mk \
  libodbc++-1-libtool.patch \
  libodbc++-1-win32.patch \
  libodbc++.mk \
  liboil.mk \
  libpano13.mk \
  libpaper-1-noundefined.patch \
  libpaper.mk \
  libpng-test.c \
  libpng.mk \
  libproxy.mk \
  librsb.mk \
  librsvg-1-fixes.patch \
  librsvg-test.c \
  librsvg.mk \
  librtmp-1-v2.4.patch \
  librtmp-2-master.patch \
  librtmp.mk \
  libsamplerate.mk \
  libshout-1-fixes.patch \
  libshout.mk \
  libsigc++.mk \
  libsndfile.mk \
  libssh2-test.c \
  libssh2.mk \
  libtool.mk \
  libunistring.mk \
  libusb.mk \
  libvpx-1-fixes.patch \
  libvpx.mk \
  libxml++.mk \
  libxml2-1-fixes.patch \
  libxml2.mk \
  libxshmfence.mk \
  libxslt.mk \
  llvm.mk \
  log4cxx-1-gcc.4.4.patch \
  log4cxx-2-pkgconfig.patch \
  log4cxx-3-warnings.patch \
  log4cxx-4-mingw.definitions.patch \
  log4cxx-5-cmake.patch \
  log4cxx-test.cpp \
  log4cxx.mk \
  lua-test.c \
  lua.mk \
  lzo.mk \
  matio.mk \
  mdbtools.mk \
  mesa-1-fixes.patch \
  mesa-proto.mk \
  mesa.mk \
  mingw-blas-1-xerbla.patch \
  mingw-cairo-1-ssize-t-defined.patch \
  mingw-cfitsio-1-fixes.patch \
  mingw-epstool-1-fixes.patch \
  mingw-glpk-1-fixes.patch \
  mingw-hdf5-1.patch \
  mingw-lapack-1-xerbla.patch \
  mingw-libgcrypt-1-fixes.patch \
  mingw-libmng-1-noundefines.patch \
  mingw-openblas-1-xerbla.patch \
  mingw-portaudio-1-pkgconfig.patch \
  mingw-s2tc-1-fixes.patch \
  mingw-texinfo-1-fixes.patch \
  mingw-utils-1-portability-fix.patch \
  mingw-w64-1-float-h.patch \
  mingw-w64.mk \
  mingwrt.mk \
  mman-win32-1-include_name_change.patch \
  mman-win32.mk \
  mpc.mk \
  mpfr.mk \
  msitools.mk \
  msvc-atk-1.patch \
  msvc-build-cmake-1.patch \
  msvc-cairo-1.patch \
  msvc-curl-1.patch \
  msvc-dbus-1.patch \
  msvc-fftw-1.patch \
  msvc-fltk-1.patch \
  msvc-fontconfig-1.patch \
  msvc-gcab-1.patch \
  msvc-gdk-pixbuf-1.patch \
  msvc-gettext-1.patch \
  msvc-gl2ps-1.patch \
  msvc-glib-1.patch \
  msvc-gnuplot-1.patch \
  msvc-gnutls-1.patch \
  msvc-graphicsmagick-1.patch \
  msvc-gsl-1.patch \
  msvc-gtk3-1.patch \
  msvc-harfbuzz-1.patch \
  msvc-hdf5-1.patch \
  msvc-itsol-1.patch \
  msvc-itstool-1.patch \
  msvc-libffi-1.patch \
  msvc-libgcrypt-1.patch \
  msvc-libgd-1.patch \
  msvc-libgpg_error-1.patch \
  msvc-libgsf-1.patch \
  msvc-libiconv-1.patch \
  msvc-libidn-1.patch \
  msvc-libmng-1.patch \
  msvc-libssh2-1.patch \
  msvc-libxml2-1.patch \
  msvc-llvm-1.patch \
  msvc-msitools-1.patch \
  msvc-msitools-2-tests.patch \
  msvc-ncurses-1.patch \
  msvc-netcdf-1.patch \
  msvc-nettle-1.patch \
  msvc-octave-1.patch \
  msvc-of-image-1.patch \
  msvc-of-miscellaneous-1.patch \
  msvc-openssl-1.patch \
  msvc-openssl-3-libdeps.patch \
  msvc-pango-1.patch \
  msvc-pixman-1.patch \
  msvc-proj-1.patch \
  msvc-pstoedit-1.patch \
  msvc-qhull-1.patch \
  msvc-qt-1.patch \
  msvc-readline-1.patch \
  msvc-suitesparse-1.patch \
  msvc-texinfo-1.patch \
  msvc-tiff-1.patch \
  msvc-vala-1.patch \
  msvc-zenity-1.patch \
  msys-bash.mk \
  msys-coreutils.mk \
  msys-diffutils.mk \
  msys-dos2unix.mk \
  msys-file.mk \
  msys-findutils.mk \
  msys-gawk.mk \
  msys-grep.mk \
  msys-gzip.mk \
  msys-less.mk \
  msys-libcrypt.mk \
  msys-libiconv.mk \
  msys-libintl.mk \
  msys-libmagic.mk \
  msys-libopenssl.mk \
  msys-make.mk \
  msys-msys-core.mk \
  msys-patch.mk \
  msys-perl.mk \
  msys-regex.mk \
  msys-sed.mk \
  msys-tar.mk \
  msys-termcap.mk \
  msys-unzip.mk \
  msys-wget.mk \
  msys-zip.mk \
  msys-zlib.mk \
  muparser.mk \
  mxml-test.c \
  mxml.mk \
  native-binutils.mk \
  native-gcc.mk \
  ncurses-1-gcc-5-fix.patch \
  ncurses.mk \
  netcdf-1-fixes.patch \
  netcdf.mk \
  nettle-1-fixes.patch \
  nettle.mk \
  npp.mk \
  nsis-2-fixes.patch \
  nsis.mk \
  ocaml-core-1-fixes.patch \
  ocaml-core-test.ml \
  ocaml-core.mk \
  ocaml-flexdll-1-fixes.patch \
  ocaml-flexdll-test.c \
  ocaml-flexdll.mk \
  ocaml-native-1-fixes.patch \
  ocaml-native.mk \
  of-actuarial.mk \
  of-audio.mk \
  of-communications.mk \
  of-control.mk \
  of-data-smoothing.mk \
  of-database.mk \
  of-dataframe.mk \
  of-dicom.mk \
  of-financial.mk \
  of-fits-1-cross-fixes.patch \
  of-fits-2-fixes.patch \
  of-fits.mk \
  of-fl-core-1-fixes.patch \
  of-fl-core.mk \
  of-fuzzy-logic-toolkit.mk \
  of-ga.mk \
  of-general.mk \
  of-generate_html.mk \
  of-geometry.mk \
  of-gsl-1-cross-fixes.patch \
  of-gsl.mk \
  of-image.mk \
  of-instrument-control.mk \
  of-interval-1-cross-fixes.patch \
  of-interval.mk \
  of-io.mk \
  of-linear-algebra.mk \
  of-lssa.mk \
  of-ltfat-1-cross-fixes.patch \
  of-ltfat.mk \
  of-matgeom.mk \
  of-mapping.mk \
  of-miscellaneous.mk \
  of-nan.mk \
  of-netcdf.mk \
  of-nurbs-1-fixes.patch \
  of-nurbs-2-dev-fixes.patch \
  of-nurbs.mk \
  of-ocs-1-cross-fixes.patch \
  of-ocs-2-dev-fixes.patch \
  of-ocs.mk \
  of-octcdf.mk \
  of-odepkg-1-fixes.patch \
  of-odepkg-2-fixes.patch \
  of-odepkg-3-deprecated.patch \
  of-odepkg.mk \
  of-optim.mk \
  of-optiminterp.mk \
  of-quaternion-1-cross-fixes.patch \
  of-quaternion-2-dev-fixes.patch \
  of-quaternion.mk \
  of-queueing.mk \
  of-signal.mk \
  of-sockets-1-cross-fixes.patch \
  of-sockets-2-deprecated.patch \
  of-sockets.mk \
  of-sparsersb.mk \
  of-specfun-1-deprecated.patch \
  of-specfun.mk \
  of-splines.mk \
  of-statistics-1-cross.patch \
  of-statistics.mk \
  of-stk.mk \
  of-strings-1-fixes.patch \
  of-strings.mk \
  of-struct.mk \
  of-symbolic.mk \
  of-tisean-1-fixes.patch \
  of-tisean.mk \
  of-tsa.mk \
  of-video-1-fixes.patch \
  of-video.mk \
  of-windows.mk \
  of-zenity.mk \
  of-zeromq.mk \
  ogg.mk \
  old.mk \
  openal-1-fixes.patch \
  openal-test.c \
  openal.mk \
  openblas.mk \
  opencore-amr.mk \
  opencsg-1-fixes.patch \
  opencsg.mk \
  opencv-1-fixes.patch \
  opencv.mk \
  openexr.mk \
  openscenegraph-1-fixes.patch \
  openscenegraph.mk \
  openssl-1-fixes.patch \
  openssl.mk \
  pango-1-fixes.patch \
  pango.mk \
  pangomm.mk \
  pcre.mk \
  pcre2.mk \
  pdcurses.mk \
  pdflib_lite-1-mingw.patch \
  pdflib_lite.mk \
  pfstools.mk \
  physfs-test.c \
  physfs.mk \
  pixman.mk \
  pkg-config.mk \
  plibc.mk \
  plotmm-1-fixes.patch \
  plotmm.mk \
  plotutils-2.6-libpng-1.5.patch \
  plotutils.mk \
  poco-1-fix-mno-cygwin.patch \
  poco-test.cpp \
  poco.mk \
  poppler-1-win32.patch \
  poppler-test.cxx \
  poppler.mk \
  popt-1-win32.patch \
  popt.mk \
  portaudio-1-win32.patch \
  portaudio-test.c \
  portaudio.mk \
  postgresql.mk \
  proj.mk \
  protobuf-test.cpp \
  protobuf.mk \
  pstoedit-1-fixes.patch \
  pstoedit-2-gs.patch \
  pstoedit-3-nosecapi.patch \
  pstoedit-4-winlibemf.patch \
  pstoedit-5-use_gs_env.patch \
  pstoedit.mk \
  pthread-stubs.mk \
  pthreads-test.c \
  pthreads.mk \
  python-embedded.mk \
  python-mpmath.mk \
  python-sympy.mk \
  qdbm-test.c \
  qdbm.mk \
  qhull-1-fixes.patch \
  qhull.mk \
  qjson-1-static.patch \
  qjson.mk \
  qrupdate-1-fixes.patch \
  qrupdate.mk \
  qscintilla-1-fixes.patch \
  qscintilla.mk \
  qt-1-cherrypicks.patch \
  qt-2-shared-tools-fixes.patch \
  qt-test.cpp \
  qt-test.pro \
  qt-test.ui \
  qt.mk \
  qt5.mk \
  qtbase-1-fixes.patch \
  qtbase.mk \
  qtimageformats.mk \
  qtsvg.mk \
  qttranslations.mk \
  qttools-1.patch \
  qttools.mk \
  qwt-1-fixes.patch \
  qwt.mk \
  qwtplot3d-1-fixes.patch \
  qwtplot3d.mk \
  readline-0-001.patch \
  readline-0-002.patch \
  readline-0-003.patch \
  readline-0-004.patch \
  readline-1-display.patch \
  readline-1-fixes.patch \
  readline-1-input.patch \
  readline-1-sigwinch.patch \
  readline-2-event-hook.patch \
  readline-2-history.patch \
  readline.mk \
  release-octave-1-gnulib.patch \
  release-octave.mk \
  renderproto.mk \
  rtmidi.mk \
  s2tc.mk \
  sdl-1-xdata.patch \
  sdl-test.c \
  sdl.mk \
  sdl_image-test.c \
  sdl_image.mk \
  sdl_mixer-test.c \
  sdl_mixer.mk \
  sdl_net-1-fixes.patch \
  sdl_net-test.c \
  sdl_net.mk \
  sdl_pango-1-api-adds.patch \
  sdl_pango-2-static-matrices.patch \
  sdl_pango.mk \
  sdl_sound-test.c \
  sdl_sound.mk \
  sdl_ttf.mk \
  sm.mk \
  smpeg-test.c \
  smpeg.mk \
  sox-test.c \
  sox.mk \
  speex.mk \
  sqlite.mk \
  src-msys-bash.mk \
  src-msys-coreutils.mk \
  src-msys-diffutils.mk \
  src-msys-dos2unix.mk \
  src-msys-file.mk \
  src-msys-findutils.mk \
  src-msys-gawk.mk \
  src-msys-grep.mk \
  src-msys-gzip.mk \
  src-msys-less.mk \
  src-msys-libcrypt.mk \
  src-msys-libiconv.mk \
  src-msys-libintl.mk \
  src-msys-libmagic.mk \
  src-msys-libopenssl.mk \
  src-msys-make.mk \
  src-msys-msys-core.mk \
  src-msys-patch.mk \
  src-msys-perl.mk \
  src-msys-regex.mk \
  src-msys-sed.mk \
  src-msys-tar.mk \
  src-msys-termcap.mk \
  src-msys-unzip.mk \
  src-msys-wget.mk \
  src-msys-zip.mk \
  src-msys-zlib.mk \
  stable-octave-1-gnulib.patch \
  stable-octave.mk \
  suitesparse-1-fixes.patch \
  suitesparse-2-metis.patch \
  suitesparse.mk \
  sundials-27-ida-1.patch \
  sundials-27-ida.mk \
  sundials-ida.mk \
  t4k_common.mk \
  taglib-1-static.patch \
  taglib.mk \
  termcap-1-fixes.patch \
  termcap.mk \
  texinfo.mk \
  theora.mk \
  tiff.mk \
  tinyxml-test.cpp \
  tinyxml.mk \
  transfig-1-fixes.patch \
  transfig.mk \
  tre.mk \
  units.mk \
  util-linux.mk \
  util-macros.mk \
  uuid.mk \
  vala.mk \
  vcdimager-1-configure.patch \
  vcdimager.mk \
  vigra-test.cpp \
  vigra.mk \
  vmime-1-fixes.patch \
  vmime.mk \
  vorbis.mk \
  vtk-1-tryrun.patch \
  vtk-2-findfreetype.patch \
  vtk-3-compile-tools.patch \
  vtk-4-native-no-gui.patch \
  vtk-5-module-path.patch \
  vtk-6-kfreebsd.patch \
  vtk.mk \
  w32api-1-dinput-dsound.patch \
  w32api-2-directx-additions-for-qt.patch \
  w32api.mk \
  wavpack-1-exec_prefix.patch \
  wavpack.mk \
  wget.mk \
  win64-nsis.patch \
  win7appid.mk \
  winpcap-1-fixes.patch \
  winpcap.mk \
  wt-1-fixes.patch \
  wt.mk \
  wxwidgets-test.cpp \
  wxwidgets.mk \
  x11.mk \
  x264-1-fix-bin-bash.patch \
  x264.mk \
  xapian-core.mk \
  xau.mk \
  xcb-proto.mk \
  xcb-util-cursor.mk \
  xcb-util-image.mk \
  xcb-util-keysyms.mk \
  xcb-util-renderutil.mk \
  xcb-util-wm.mk \
  xcb-util.mk \
  xcb.mk \
  xcursor.mk \
  xdamage.mk \
  xdmcp.mk \
  xerces-1-fix-pkgconfig.patch \
  xerces-test.cpp \
  xerces.mk \
  xext.mk \
  xextproto.mk \
  xf86vidmodeproto.mk \
  xfixes.mk \
  xft.mk \
  xi.mk \
  xine-lib-1-configure_ac.patch \
  xine-lib-2-build_fixes.patch \
  xine-lib-3-more_build_fixes.patch \
  xine-lib-4-mkdir.patch \
  xine-lib-5-change_mma_h_to_mma_win32_h.patch \
  xine-lib.mk \
  xkbcommon-1-fixes.patch \
  xkbcommon.mk \
  xmlwrapp.mk \
  xproto.mk \
  xrender.mk \
  xt.mk \
  xtrans.mk \
  xvidcore.mk \
  xxf86vm.mk \
  xz.mk \
  yasm.mk \
  zenity.mk \
  zeromq.mk \
  zlib-1-win32-static.patch \
  zlib.mk \
  zziplib-1-fix-fnmatch.patch \
  zziplib.mk

SRC_FILES := $(addprefix src/, $(SRC_FILES_1))

SRC_MSVCTOOLS_FILES_1 := \
  ar-msvc \
  cc-msvc.cc \
  fixlibtool2.in \
  gcc.diff \
  gfortran-msvc.cc \
  libgfortran-dllinit.c \
  libgfortran-msvcinit.c \
  lt-postproc \
  Makefile \
  ranlib-msvc \
  stdbool.h \
  unistd.h \
  Windows-clg++.cmake \
  Windows-clgcc.cmake.in

SRC_MSVCTOOLS_FILES := $(addprefix src/build-msvctools/, $(SRC_MSVCTOOLS_FILES_1))

SRC_MSVCTOOLS_COMPAT_FILES_1 := \
  cabsf.c \
  ccos.c \
  ccosf.c \
  cexp.c \
  cexpf.c \
  clog.c \
  clogf.c \
  csin.c \
  csinf.c \
  csqrt.c \
  csqrtf.c \
  gettimeofday.c \
  Makefile \
  mingwcompat.c \
  mingwcompat_gcc.c \
  usleep.c

SRC_MSVCTOOLS_COMPAT_FILES := \
  $(addprefix src/build-msvctools/compat/, $(SRC_MSVCTOOLS_COMPAT_FILES_1))

SRC_MSVCTOOLS_MATH_FILES_1 := \
  acosh.c \
  acoshf.c \
  asinh.c \
  asinhf.c \
  atanh.c \
  atanhf.c \
  cbrt.c \
  cbrtf.c \
  cephes_mconf.h \
  exp2f.S \
  exp2.S \
  expm1.c \
  expm1f.c \
  fastmath.h \
  finite.c \
  finitef.c \
  fmaf.S \
  fma.S \
  fpclassify.c \
  fpclassifyf.c \
  funx.c \
  ilogbf.S \
  ilogb.S \
  isinf.c \
  isinff.c \
  isnan.c \
  isnanf.c \
  llrint.c \
  llrintf.c \
  log1pf.S \
  log1p.S \
  log2f.S \
  log2.S \
  logb.c \
  logbf.c \
  lrint.c \
  lrintf.c \
  lround_generic.c \
  Makefile \
  math.def \
  math.h.in \
  modff.c \
  nan.c \
  nearbyintf.S \
  nearbyint.S \
  nextafter.c \
  nextafterf.c \
  remainderf.S \
  remainder.S \
  rint.c \
  rintf.c \
  round_generic.c \
  round_internal.h \
  scalbnf.S \
  scalbn.S \
  trunc.c \
  truncf.c

SRC_MSVCTOOLS_MATH_FILES := \
  $(addprefix src/build-msvctools/math/, $(SRC_MSVCTOOLS_MATH_FILES_1))

SRC_MSYS2_FILES_1 := \
  msys2-bash.mk \
  msys2-coreutils.mk \
  msys2-diffutils.mk \
  msys2-dos2unix.mk \
  msys2-filesystem.mk \
  msys2-findutils.mk \
  msys2-gawk.mk \
  msys2-gcc-libs.mk \
  msys2-gmp.mk \
  msys2-gnupg.mk \
  msys2-grep.mk \
  msys2-gzip.mk \
  msys2-icu.mk \
  msys2-info.mk \
  msys2-keyring.mk \
  msys2-less.mk \
  msys2-libassuan.mk \
  msys2-libbz2.mk \
  msys2-libcrypt.mk \
  msys2-libexpat.mk \
  msys2-libffi.mk \
  msys2-libgnutls.mk \
  msys2-libgcrypt.mk \
  msys2-libgpg-error.mk \
  msys2-libgpgme.mk \
  msys2-libhogweed.mk \
  msys2-libiconv.mk \
  msys2-libidn2.mk \
  msys2-libintl.mk \
  msys2-libksba.mk \
  msys2-liblzma.mk \
  msys2-libmetalink.mk \
  msys2-libnettle.mk \
  msys2-libnpth.mk \
  msys2-libopenssl.mk \
  msys2-libp11-kit.mk \
  msys2-libpcre.mk \
  msys2-libpcre2.mk \
  msys2-libpsl.mk \
  msys2-libreadline.mk \
  msys2-libsqlite.mk \
  msys2-libtasn1.mk \
  msys2-libunistring.mk \
  msys2-libutil-linux.mk \
  msys2-libxml2.mk \
  msys2-make.mk \
  msys2-mintty.mk \
  msys2-mpfr.mk \
  msys2-ncurses.mk \
  msys2-pacman-mirrors.mk \
  msys2-pacman.mk \
  msys2-patch.mk \
  msys2-perl.mk \
  msys2-runtime.mk \
  msys2-sed.mk \
  msys2-tar.mk \
  msys2-unzip.mk \
  msys2-wget.mk \
  msys2-zip.mk \
  msys2-zlib.mk

SRC_MSYS2_FILES := \
  $(addprefix src/, $(SRC_MSYS2_FILES_1))

SRC_MSYS2_SRC_FILES_1 := \
  src-msys2-bash.mk \
  src-msys2-coreutils.mk \
  src-msys2-diffutils.mk \
  src-msys2-dos2unix.mk \
  src-msys2-filesystem.mk \
  src-msys2-findutils.mk \
  src-msys2-gawk.mk \
  src-msys2-gcc-libs.mk \
  src-msys2-gmp.mk \
  src-msys2-gnupg.mk \
  src-msys2-grep.mk \
  src-msys2-gzip.mk \
  src-msys2-icu.mk \
  src-msys2-info.mk \
  src-msys2-keyring.mk \
  src-msys2-less.mk \
  src-msys2-libassuan.mk \
  src-msys2-libbz2.mk \
  src-msys2-libcrypt.mk \
  src-msys2-libexpat.mk \
  src-msys2-libffi.mk \
  src-msys2-libgcrypt.mk \
  src-msys2-libgnutls.mk \
  src-msys2-libgpg-error.mk \
  src-msys2-libgpgme.mk \
  src-msys2-libhogweed.mk \
  src-msys2-libiconv.mk \
  src-msys2-libidn2.mk \
  src-msys2-libintl.mk \
  src-msys2-libksba.mk \
  src-msys2-liblzma.mk \
  src-msys2-libmetalink.mk \
  src-msys2-libnettle.mk \
  src-msys2-libnpth.mk \
  src-msys2-libopenssl.mk \
  src-msys2-libp11-kit.mk \
  src-msys2-libpcre.mk \
  src-msys2-libpcre2.mk \
  src-msys2-libpsl.mk \
  src-msys2-libreadline.mk \
  src-msys2-libsqlite.mk \
  src-msys2-libtasn1.mk \
  src-msys2-libunistring.mk \
  src-msys2-libutil-linux.mk \
  src-msys2-libxml2.mk \
  src-msys2-make.mk \
  src-msys2-mintty.mk \
  src-msys2-mpfr.mk \
  src-msys2-ncurses.mk \
  src-msys2-pacman-mirrors.mk \
  src-msys2-pacman.mk \
  src-msys2-patch.mk \
  src-msys2-perl.mk \
  src-msys2-runtime.mk \
  src-msys2-sed.mk \
  src-msys2-tar.mk \
  src-msys2-unzip.mk \
  src-msys2-wget.mk \
  src-msys2-zip.mk \
  src-msys2-zlib.mk

SRC_MSYS2_SRC_FILES := \
  $(addprefix src/, $(SRC_MSYS2_SRC_FILES_1))

TOOLS_FILES_1 := \
  build-make.sh \
  config.guess \
  config.sub \
  create-screenshot-for-doc \
  install-sh \
  make-shared-from-static \
  makeinst-script.sh.in \
  mk-hg-id.sh \
  msys2-install.py \
  patch-tool-mxe \
  pkg-install.py \
  s3-fetch-and-sync \
  set-mxe-env.sh.in \
  gen-bat-wrapper

TOOLS_FILES := $(addprefix tools/, $(TOOLS_FILES_1))

FILES := \
  $(TOP_BUILD_DIR)/HG-ID \
  CNAME \
  README \
  aclocal.m4 \
  binary-dist-rules.mk \
  bootstrap \
  build_packages.m \
  configure \
  configure.ac \
  dist-files.mk \
  hg-octave-dist.mk \
  index.html \
  Makefile.in \
  octave-wrapper.in \
  octaverc

INSTALL_FILES_1 := \
  cmdshell.bat \
  post-install.bat \
  fc_update.bat \
  gpl-3.0.txt \
  octave.bat \
  octave.bmp \
  octave.vbs \
  octave-firsttime.vbs \
  octave-hdr.bmp \
  octave-logo.ico \
  post-install.bat \
  README.html
INSTALL_FILES := $(addprefix installer-files/, $(INSTALL_FILES_1))

DIST_FILES := \
  $(SRC_FILES) \
  $(SRC_MSYS2_FILES) \
  $(SRC_MSYS2_SRC_FILES) \
  $(SRC_MSVCTOOLS_FILES) \
  $(SRC_MSVCTOOLS_COMPAT_FILES) \
  $(SRC_MSVCTOOLS_MATH_FILES) \
  $(TOOLS_FILES) \
  $(FILES) \
  $(INSTALL_FILES)


