#!/bin/bash

prefix=
suffix=

while getopts ":p:s:" opt; do
	case $opt in
		s) suffix="$OPTARG" ;;
		p) prefix="$OPTARG" ;;
	esac
done
shift $((OPTIND-1))

if [ "$1" = "" ]; then
	libtool_files=`find . -name libtool`
else
	libtool_files="$@"
fi

for ltfile in $libtool_files; do
	sed -i \
		-e "s/^soname_spec=\"\\(.*\\)\\\${shared_ext}\"/soname_spec=\"$prefix\\1$suffix\\\${shared_ext}\"/" \
		-e "s/\.dll\.lib/\.lib/" \
		-e "s/^\(deplibs_check_method\)=.*/\1=\"pass_all\"/" \
		-e "s/-link\\>//" \
		$ltfile
done
